val_0:
  _target_: mining_sites.helpers.dataset_helpers.DatasetOriginal
  dataset_root: data/images/competition_data
  ann_path: data/annotations/fold_0.csv
  split: val

val_1:
  _target_: mining_sites.helpers.dataset_helpers.DatasetOriginal
  dataset_root: data/images/competition_data
  ann_path: data/annotations/fold_1.csv
  split: val

val_2:
  _target_: mining_sites.helpers.dataset_helpers.DatasetOriginal
  dataset_root: data/images/competition_data
  ann_path: data/annotations/fold_2.csv
  split: val
