- _target_: mining_sites.callbacks.model.ChangeModelDevice
- _target_: mining_sites.callbacks.model.TrainEval
- _target_: mining_sites.callbacks.model.SaveModel
  top_k: 5
- _target_: mining_sites.callbacks.logging.CalculateETA
- _target_: mining_sites.callbacks.logging.LogMetrics_Mlflow
- _target_: mining_sites.callbacks.model.EMA
  ema_decay_per_epoch: 0.3
- _target_: mining_sites.callbacks.model.LoadModelFromDisk
  path: /mnt/sota/mlflow_artifact_store/200921760190976169/98a09502a78a4706b99325fe653aac55/artifacts/epoch_19_f1_score_0.76259.pt
