defaults:
  - _self_
  - trainer: test
  - model: smp_unet_maxvit_mask_center_offsets
  - accelerate: gpu_amp
  - dataset: [test/test]
  - loader: b2_w2
  - collate_fn:
  - sampler: distributed
  - transform: identity
  - hydra: default
